### PR TITLE
[WIP] Update for jlab-2.0

### PR DESCRIPTION
**Pull request by blink1073**
Switch to a variables-only theme for now.  We can later add icons that use `JLIcon`.

### CODE REVIEW

**Comment by telamonian** [comment]
>  We can later add icons that use `JLIcon`

I was thinking the same thing

**Comment by telamonian** [comment]
It's probably the `clean` step in the `prepare` script in `package.json` that's screwing up the extension install during the CI... and I see you beat me to it

**Comment by telamonian** [comment]
LGTM! Lemme just preserve the pre-existing master on the `jlab-1.0` branch and then I'll pull this in

**Comment by telamonian** [comment]
@blink1073 Thanks for the updates, and especially for figuring out the CI! Is this still WIP, or is it ready to merge?

**Comment by blink1073** [comment]
Let's go ahead and merge the cookie cutter updates now.

**Pull request merged**
